language: c

install:
  - scversion="stable"
  - wget "https://storage.googleapis.com/shellcheck/shellcheck-$scversion.linux.x86_64.tar.xz"
  - tar --xz -xvf "shellcheck-$scversion.linux.x86_64.tar.xz"
  - shellcheck() { "shellcheck-$scversion/shellcheck" "$@"; }

before_script:
    - shellcheck --version

script:
    - source ${TRAVIS_BUILD_DIR}/build.sh
